postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: password
  PostgresqlDbname: database

redis:
  RedisHost: localhost
  RedisPort: 6379
  RedisUser:
  RedisPassword:
  RedisDB: 0

rabbitmq:
  username: vercello
  password: vercello
  host: localhost
  port: 5672
  exchangeName: emails-exchange
  queueName: emails-queue
  consumerTag: emails-consumer
  bindingKey: emails-routing-key


app:
  jwt:
    secret: yata_auth_key
    token_ttl_hours: 12
    salt: yata_vercello_salt
  port: 3999
  email-endpoint: http://localhost:8080/api/user/activate

