postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: password
  PostgresqlDbname: database

redis:
  RedisHost: localhost
  RedisPort: 6379
  RedisUser:
  RedisPassword:
  RedisDB: 0


app:
  jwt:
    secret: yata_auth_key
    token_ttl_hours: 12
    salt: yata_vercello_salt
  port: 3999

